# Generated by Django 3.2.4 on 2021-06-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20210616_1350"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
